### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by julienvincent** [giraud/reasonml-idea-plugin#1]
Thanks for your work on getting ReasonML support to IDEA.

I was wondering if you could describe a roadmap/timeline for what still needs to be completed and estimates on when this will be ~complete?

As of now this is the only public attempt at getting support to IDEA and it will be great to see this implemented.

**Comment by giraud** [comment]
Hi, I have no roadmap at all right now. 

My goal is to be able to edit reason files with the editor I use at work: so basic functionalities. After that I dont know yet.

And I have very few hours to work on it, I can't give you estimates.

**Comment by julienvincent** [comment]
Alright no worries :) Cool to at least see someone working on it 👍

**Comment by giraud** [comment]
I'm closing this issue: I have created a TODO list.
