### ISSUE TITLE
Enhancement: support .mlg files

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#118]
plugin version: 0.67.2

### Description Support .mlg files

.mlg files specify the grammar for a parser.  They generally include a bunch of embedded OCaml.  It would be great if syntax highlighting, comment a line/block and some of the other basic features worked in .mlg files.

Even better would be to populate the structure panel with the pure OCaml items that appear before `GRAMMAR EXTEND Gram`.  And with a bit more work, maybe include grammar symbol definitions in the structure panel.

Here is an example .mlg file: https://github.com/coq/coq/blob/master/plugins/ltac/g_tactic.mlg

**Comment by giraud** [comment]
done.
![image](https://user-images.githubusercontent.com/239612/49082980-8608e900-f24b-11e8-86b0-8a4f2314b68a.png)

but the grammar section is totally foreign to me. is there any grammar :wink: that describe it ?

**Comment by jfehrle** [comment]
Thanks, that's much better.  The comment/uncomment operations don't work, though.

When I put in the request, I thought .mlg was a general-purpose format, but then I realized that it's specific to the Coq project.  Whatever support you can provide would be great, but it may not be something you want to spend much time on.

Nonetheless, the grammar file is in https://github.com/coq/coq/tree/master/coqpp.  Looks like coqpp_parse.mly is the yacc input file, coqpp_lex.mll is the lex input file.

It would also be helpful if the plugin supported .mll and .mly files to some degree--they are general purpose formats though I don't know how widely they're used in OCaml.

**Comment by giraud** [comment]
I added some highlighting to mll mly.
if needed, create more specific issues, thanks.

**Comment by giraud** [comment]
Not working anymore in 0.113, need to implement the same host injection like what has been done in mll/mly

**Comment by giraud** [comment]
better parsing of mlg, with correct ocaml parser used in injection blocks. support syntax highlighting and folding.
![image](https://github.com/giraud/reasonml-idea-plugin/assets/239612/b5328085-7b71-4691-9253-729a2d602d02)
