### ISSUE TITLE
Params popup is showing names from code instead of types

### ISSUE THREAD

**Issue by Coobaha** [giraud/reasonml-idea-plugin#157]
plugin version: 
0.74
### Description
Should it be showing types too? Or some combined version?

![image](https://user-images.githubusercontent.com/2446638/54940298-24c00080-4f33-11e9-8c7c-cea49f1d9ad9.png)

![image](https://user-images.githubusercontent.com/2446638/54940043-a06d7d80-4f32-11e9-899e-7746389068e1.png)

**Comment by JohnPucciarelli** [comment]
https://www.jetbrains.com/help/idea/viewing-reference-information.html#view-parameter-info

**Comment by giraud** [comment]
parameter info reworked, it'll only show types.
