### ISSUE TITLE
Showing wrong module for autocomplition

### ISSUE THREAD

**Issue by Coobaha** [giraud/reasonml-idea-plugin#201]
plugin version: 
0.83
### Description
Having (not using) library that has for example `List` module confuses indexing.

`List.` suggestions are showing this library scope, while it should show `stdlib List`

**Comment by giraud** [comment]
realted to #186 ?

**Comment by Coobaha** [comment]
Yeah both issues are about naive indexing (without intelligence of actually used modules)
