### ISSUE TITLE
Process "include" statements to locate symbols

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#248]
plugin version: 0.88.1-2020.1

The plugin doesn't interpret `include` statements at all.  For example, `Pcoq.ml` has an `include Grammar.GMake(CLexer.Lexer)` in it, however you can't jump to the definition of symbols such as `Rule` and `Symbol` defined in `Grammar.ml`, nor do they appear in the structure panel for `Pcoq.ml`.
(examples from https://github.com/coq/coq).

Below are some examples from parsing code generated for Coq.

I see you've taken on a few contributors.  How hard would it be for me to rework some of the code analysis to address this and a couple related issues I've submitted?  Seems like it would be mostly or entirely data structure manipulation.  I did Java for about 10 years.  I'm quite familiar with yacc/antlr-like parsers and also somewhat with OCaml parsers.  I've done a couple years with Swing, too.  I've not seriously developed IJ plugins, though.

What do you think?  I suppose the first step for me would be to look at the relevant code and see what I would be getting into.

```
let _ = let () =
        Pcoq.grammar_extend ssrbinder
        { Pcoq.pos=None; data=[(None, None,
                               [Pcoq.Production.make
                                (Pcoq.Rule.next (Pcoq.Rule.next (Pcoq.Rule.stop)
                                                                ((Pcoq.Symbol.rules 
                                                                [Pcoq.Rules.make 
                                                                (Pcoq.Rule.next_norec 
                                                                (Pcoq.Rule.stop)
                                                                ((Pcoq.Symbol.token (Tok.PKEYWORD ("&")))))
                                                                (fun _ loc ->
                                                                
# 1340 "plugins/ssr/ssrparser.mlg"
                                () 
                                                                );
```

**Comment by giraud** [comment]
This one is not working, because it is a functor. same problem than #205 I guess.
Still in the pipe, not started yet, because I try to release a new version of the plugin first.

I think you have everything needed to contribute to this project :). And contributions are always welcome.
Most of the work is in in the indexing and referencing PSI structures. when done correctly, a lot of features are automagically available. Also the parser (not the best part of the plugin) need to be updated regularly. I am still learning IntelliJ plugin architecture while working on this plugin. 

I'd like to add a doc like the one for [rust](https://github.com/intellij-rust/intellij-rust/blob/master/ARCHITECTURE.md), but it's not a small part, and it takes time for a non native english speaker.

The best thing to do now is to ping me in dicord and ask me questions.

**Comment by jfehrle** [comment]
> I'd like to add a doc like the one for rust, but it's not a small part, and it takes time for a non native english speaker.

When you have a draft I'd be happy to review that for clarity and completeness as well as copy editing it to get idiomatic English.

**Comment by giraud** [comment]
@jfehrle some docs are being written in the docs/ subdirectory. ex: [architecture](https://github.com/reasonml-editor/reasonml-idea-plugin/blob/master/docs/Architecture.md)

**Comment by jfehrle** [comment]
How do I locate you in discord?  I've never used it.  I'm in California.  If you're in France, then we're 9 hours off--we may not be active at the same time.  I lean more on GitHub issues email to communicate.

Also, would you send me your email address?  Mine is com gmail at fehrle jim, more or less.

**Comment by jfehrle** [comment]
What heap size do I need?  I 'm still getting a failure with 4GB.

![image](https://user-images.githubusercontent.com/1253341/82722527-88030b00-9c7c-11ea-8742-81664337205a.png)

Also, what settings should I use in `plugin.xml`?

**Comment by jfehrle** [comment]
The source code I mentioned.  I had to add ".txt" to the suffix so GitHub would let me upload the file.

[ssrparser.ml.txt](https://github.com/reasonml-editor/reasonml-idea-plugin/files/4773133/ssrparser.ml.txt)

**Comment by giraud** [comment]
I’m closing this issue bc with 0.112, from pcoq.ml you can go to Rule or Symbol in grammar.ml. 
It is slower than wanted right now but reference is resolved.
