### ISSUE TITLE
`bs-platform` is getting renamed to `rescript`

### ISSUE THREAD

**Issue by hoichi** [giraud/reasonml-idea-plugin#318]
plugin version: 0.99-2021.1

### Description

The npm package for ReScript (which includes the ex-BuckleScript compiler & libs) is [being renamed](https://forum.rescript-lang.org/t/ann-rescript-9-1-for-beta-testing-windows-testing-welcome/1427) from `bs-platform` to `rescript`. If you install it and remove `bs-platform`, the current version of plugin cannot find `bs-platform` even if you point it to `node_modules/rescript`.

Sure, ReScript 9.1 is still in beta, so I'm not complaining the plugin doesn't support it. Just a heads up.

**Comment by giraud** [comment]
no problem.
I put rescript dev in pause mainly because of the stdin problem, but since it is now fixed I will restart some work on it. But first I am in a process of redesigning ref resolution for #303 and I need to finish that first.

**Comment by giraud** [comment]
need #328 first

**Comment by giraud** [comment]
format on save ok. work on tool window

**Comment by giraud** [comment]
if you want to test a beta version: https://filebin.net/nexpy29skjzcu2hy

**Comment by dsiu** [comment]
> if you want to test a beta version: https://filebin.net/nexpy29skjzcu2hy

`01:35	Plugin error: Plugin 'ReasonML' (version '0.102-318-03-2020.2') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-211.7442.40`

I love to test it since I have been waiting, but it isn't compatible with IntelliJ 2021.1.2.  Thanks for putting in the time to get it working with `rescript`

**Comment by dsiu** [comment]
I managed to get it working with 2021.1.2 using the filebin build.  found a syntax coloring bug whenever string interpolation is used.  All code line after the first string interpolation would not work.

It should code color like this:
<img width="509" alt="Screen Shot 2021-06-23 at 01 53 40" src="https://user-images.githubusercontent.com/74945/122975968-797aac00-d3c6-11eb-9deb-50251b482038.png">

but it showed:
<img width="509" alt="Screen Shot 2021-06-23 at 01 53 31" src="https://user-images.githubusercontent.com/74945/122975994-80a1ba00-d3c6-11eb-8c94-00172ff535c9.png">

**Comment by giraud** [comment]
ah yes, sorry, dev is on minimal version only. I merge with latest versions just before I release.
also, focusing on the integration with rescript. this version wont' fix everything.

**Comment by hoichi** [comment]
> I managed to get it working with 2021.1.2 using the filebin build.

How did you do it? Did it involve building Java? :worried:

**Comment by giraud** [comment]
@dsiu fixed the interpolation issue https://filebin.net/iubauahl72cwh98o

**Comment by dsiu** [comment]
> @dsiu fixed the interpolation issue https://filebin.net/iubauahl72cwh98o

Thanks, @giraud ! it was a super quick turnaround.  now I will focus on testing out other functionalities.

**Comment by giraud** [comment]
@hoichi beta for 2021.1: https://filebin.net/id9xdxlmjyuvo7ob

**Comment by giraud** [comment]
note: `@rescript/react` is not indexed in this beta. I have the fix locally.

**Comment by hoichi** [comment]
Tested it with `rescript 9.1.4`. Looking good so far. Grand merci!

**Comment by hoichi** [comment]
Found a minor bug: the tool window is called `Recript`.

**Comment by giraud** [comment]
fixed in 0.102
