### ISSUE TITLE
"Comment with line comment" action incorrect for lines ending with "("

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#319]
plugin version: 0.99-2020.3

For a line ending with "(", the "Comment with line comment" action (CTRL-/) should add " \*)" rather than "\*)".  The latter results in "(*)", which OCaml interprets as the beginning of a nested comment.

**Comment by giraud** [comment]
fixed in 0.111

**Comment by jfehrle** [comment]
Looks good, thanks!
