### ISSUE TITLE
Class types in .mli files should link to the corresponding definition in the .ml file

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#322]
plugin version: 0.99-2021.1

`proof_view` on the first line should have a gutter icon linking it to the corresponding definition in the .ml file

![image](https://user-images.githubusercontent.com/1253341/115915918-dee30880-a428-11eb-81a0-7e62eeca9a08.png)

**Comment by giraud** [comment]
fixed in 0.103

**Comment by jfehrle** [comment]
Looks good, thanks!
