### ISSUE TITLE
Structure panel shows "mutable" for mutable record fields rather than the field name

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#326]
plugin version: 0.99-2021.1

The structure panel should show `debug_stop_pt` and `breakpoints` rather than `mutable` (twice).

![image](https://user-images.githubusercontent.com/1253341/117523068-b0f2dd80-af6b-11eb-8150-c0c057cdffc4.png)

**Comment by giraud** [comment]
fixed in 0.102
