### ISSUE TITLE
Bug with the interface recognition

### ISSUE THREAD

**Issue by Butanium** [giraud/reasonml-idea-plugin#330]
plugin version: 0.101-2021.1

since the last update the interface between .ml and .mli is completely bugged see :

![h2ogJredJ2](https://user-images.githubusercontent.com/55806347/120678610-92afcd00-c498-11eb-9d24-a5d63dc46c63.gif)

**Comment by giraud** [comment]
do you have a minimal repro code for that ?

**Comment by giraud** [comment]
no repro
