### ISSUE TITLE
website not found 404

### ISSUE THREAD

**Issue by giraud** [giraud/reasonml-idea-plugin#331]
whaat?

**Comment by outkine** [comment]
Bumping this, https://reasonml-editor.github.io/reasonml-idea-plugin/ 404s

**Comment by JoAllg** [comment]
yes, documentation is offline :-(

**Comment by JoAllg** [comment]
The documentation also accessible here https://github.com/giraud/reasonml-idea-plugin/tree/master/website/docs by the way

**Comment by giraud** [comment]
I forgot to update the domain of gh-pages after moving project from reasonml-editor

**Comment by JoAllg** [comment]
The Github About Sidebar still links to the old domain

**Comment by giraud** [comment]
thank you, fixed
