### ISSUE TITLE
WSL support?

### ISSUE THREAD

**Issue by jgjl** [giraud/reasonml-idea-plugin#338]
plugin version: 0.102.1-2021.1

### Description
Hi, I am trying to use the plugin on Windows. Since the native Ocaml version for Ocaml will be deprecated soon (https://fdopen.github.io/opam-repository-mingw/) I tried to use the WSL version. Using the WSL binaries directly as well as setting `bash.exe` with the Cygwin option yields the error message: "Opam: Can't find sdk".

Any ideas how to make this work?

**Comment by giraud** [comment]
you need to define an ocaml sdk (https://giraud.github.io/reasonml-idea-plugin/docs/language-support/ocaml).
unfortunately, ocaml/dune projects need many manual config right now

**Comment by jgjl** [comment]
Thank you for the information! I did miss the details about WSL, thanks!
