### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by QuentinRa** [giraud/reasonml-idea-plugin#341]
Hi, thanks for the plugin, just so you know, both these links are dead

- [x] [ReasonML](https://plugins.jetbrains.com/plugin/9440-reasonml) > "Documentation"
  - from https://reasonml-editor.github.io/reasonml-idea-plugin/
  - expected? https://giraud.github.io/reasonml-idea-plugin/
- [x] CONTRIBUTING.md
  - from https://reasonml-editor.github.io/reasonml-idea-plugin/docs/contributing/how-to-contribute
  - expected? https://giraud.github.io/reasonml-idea-plugin/docs/contributing

**Comment by giraud** [comment]
thank you !
