### ISSUE TITLE
Pycharm Compatibility

### ISSUE THREAD

**Issue by JoAllg** [giraud/reasonml-idea-plugin#346]
Though some people stated in older issues, that they got ReasonML running in Pycharm, I am not able to find out how to do it:
Pycharm doesn't has the Project Structure Dialog where the facets and SDKs can be set and therefore I can't configure ReasonML.
Am i missing something or is it not compatible anymore?

**Comment by giraud** [comment]
It depends on your project, pycharm is compatible if you are using bucklescript or rescript.
For OCaml projects (dune), only IntelliJ is supported.

I realize there might be a misleading message when one edit a ml file in a bucklescript project tho.

**Comment by JoAllg** [comment]
Ok good to know, since I am using Ocaml/dune I will have to stay with Intellij. I wanted to use Pycharm because there are other accompanying plugins for Pycharm that are connected with my project ( tezos, michelson, jupyter).

Thanks for your reply :-)

**Comment by QuentinRa** [comment]
@JoAllg If you are ever interested in moving from dune to BuckleScript, maybe my [tutorial will be helpful](https://github.com/memorize-code/jetbrains-ocaml-setup).
