### ISSUE TITLE
Use declaration documentation if no local documentation

### ISSUE THREAD

**Issue by QuentinRa** [giraud/reasonml-idea-plugin#350]
If there is no local documentation, the documentation of the declaration should be used instead. As we have in Java.

![image](https://user-images.githubusercontent.com/54904135/133622216-73b1e757-60f0-49ee-b4ae-53b909bcde8a.png)

![image](https://user-images.githubusercontent.com/54904135/133623041-f4a6a911-0a12-4bec-ab6c-16dc6e0a2b56.png)

_Originally posted by @QuentinRa in https://github.com/giraud/reasonml-idea-plugin/discussions/349#discussioncomment-1342391_

**Comment by giraud** [comment]
fixed in 0.111
