### ISSUE TITLE
Can't download rincewind_w4.13.1-0.9.1.exe

### ISSUE THREAD

**Issue by JoAllg** [giraud/reasonml-idea-plugin#363]
plugin version: 0.104-2021.2

### Description
Using OCaml SDK 4.13.1 and dune, the plugin tries and fails to dowload rincewind:
```Can't download C:\Users\Joshua\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5457.46.plugins\reasonml-idea-plugin\rincewind_w4.13.1-0.9.1.exe java.io.FileNotFoundException: https://rincewind.jfrog.io/artifactory/ocaml/rincewind_w4.13.1-0.9.1.exe```
Is 4.13.1 not supported by ReasonML currently?

**Comment by giraud** [comment]
forgot about it, i'll update.

**Comment by giraud** [comment]
4.13.1 is available. 
but you must update your plugin. this is old.
