### ISSUE TITLE
https://youtrack.jetbrains.com/issue/IDEA-307528

### ISSUE THREAD

**Issue by SLukashenko** [giraud/reasonml-idea-plugin#393]
plugin version: 

### Description
https://youtrack.jetbrains.com/issue/IDEA-307528

**Comment by giraud** [comment]
Hi, this is a plugin exception, I don’t think it is a good thing to add an issue to the jira tracker.
also, please add the plugin version in this github bug

**Comment by SLukashenko** [comment]
Unfortunately user has not added log files nor reported plugin version. If we have similar issues reported with log files I will let you know plugin version.

**Comment by nahoj** [comment]
plugin version: 0.112-2023.1

It seems I just got the same error. I think it happened when I upgraded the plugin from 0.111 to 0.112. The 4 new `PsiLetStub` near the top of `stubTreeFromIndex.txt` match newly supported operator declarations (https://github.com/giraud/reasonml-idea-plugin/issues/407).

[stacktrace.txt](https://github.com/giraud/reasonml-idea-plugin/files/11405287/stacktrace.txt)
[0pen.ml_file.txt](https://github.com/giraud/reasonml-idea-plugin/files/11405289/0pen.ml_file.txt)
[stubTree.txt](https://github.com/giraud/reasonml-idea-plugin/files/11405292/stubTree.txt)
[stubTreeFromIndex.txt](https://github.com/giraud/reasonml-idea-plugin/files/11405294/stubTreeFromIndex.txt)

**Comment by giraud** [comment]
maybe because the file is parsed differently now. other than that, I don’t know

**Comment by giraud** [comment]
I think it’s a plugin problem, but it’s an internal error of intellij and I don’t know how to fix it
