### ISSUE TITLE
Bad parsing of `if` in method (OCaml)

### ISSUE THREAD

**Issue by nahoj** [giraud/reasonml-idea-plugin#405]
plugin version: 0.110-2023.1

### Description

In the Structure tool window for the following code, `x` appears as a top-level declaration instead of being a member of `M`.

```ocaml
module M = struct
  let o = object
    method m =
      if 2 > 1 then ()
  end
  let x = 0
end
```

- test.ml
  - M
    - o
  - x

Whereas if I replace the `if` line with `if true then ()` then the structure is correct:

- test.ml
  - M
    - o
    - x

**Comment by giraud** [comment]
fixed in 0.111

**Comment by nahoj** [comment]
Thank you!

**Comment by nahoj** [comment]
@giraud Thank you for fixing this, and for making this plugin which I've been using frequently in the past few weeks :)

Over time I noticed a few other bugs in the structure parsing. Is that the kind of thing you're willing to fix? Should I open issues for each of them? (Or one big issue?)

Cheers

**Comment by giraud** [comment]
@nahoj thanks, and yes, please, add github issues for parsing problems. I don’t use OCaml and won't detect them.
