### ISSUE TITLE
`let ... in` not shown in `let a = ...` structure (OCaml)

### ISSUE THREAD

**Issue by nahoj** [giraud/reasonml-idea-plugin#408]
plugin version: 0.111-2023.1

### Description

A `let ... in` doesn't appear in a value declaration, whereas it does in a function declaration.

```ocaml
let a =
  let x = 0 in
  x

let f () =
  let x = 0 in
  x
```

- test.ml
  - a
  - f
    - x

**Comment by giraud** [comment]
Fixed in 0.112
