### ISSUE TITLE
Wrong structure on `let b = 1 = 1 in` (OCaml)

### ISSUE THREAD

**Issue by nahoj** [giraud/reasonml-idea-plugin#409]
plugin version: 0.111-2023.1

### Description

This code is parsed into the wrong structure:

```ocaml
let f () =
  let b : bool = 1 = 1 in
  let x = 0 in
  x
```

- test.ml
  - f
    - b
  - x

**Comment by giraud** [comment]
Fixed in 0.112

**Comment by nahoj** [comment]
It looks like the fix doesn't support general expressions, e.g.:

```ocaml
let f () =
  let b : bool = ignore () = () in
  let x = 0 in
  x
```

- test.ml
  - f
    - b
  - x

Thank you for all the other fixes; that was fast!

**Comment by giraud** [comment]
@nahoj can you test with 0.113 please ?

**Comment by nahoj** [comment]
It works on the previous example, but not on this one:

```ocaml
let f () =
  let b : bool = ignore "" = () in
  let x = 0 in
  x
```

**Comment by giraud** [comment]
It should be ok in 0.115

**Comment by nahoj** [comment]
Thank you.
