### ISSUE TITLE
Block comment operation (Ctrl-Shift-/) on highlighted text should not add a newline

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#411]
plugin version: 0.112-2023.1
This behavior seems to have started when I installed 0.111.

### Description

The "after" should show `(*of*)` or better `(* of *)` without adding a newline.

before:
![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/a2ec8c63-da84-455b-838c-ce8baa4306c5)

after:
![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/3c521404-5416-46a2-bb2c-ab0fed7364ea)

**Comment by giraud** [comment]
fixed in 0.113

**Comment by jfehrle** [comment]
Fix works, thanks!
