### ISSUE TITLE
Lets in toplevel let: shouldn't show loc, k and x in the Structure panel

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#415]
plugin version: 0113-2023.1

### Description

Was this perhaps intentional?  It ~doesn't~ seems to show every let in functions.  If I duplicate the `x` line, there are 2 entries for `x` in the structure panel.

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/0ed43b49-9427-47f1-9f45-c4ce5b3db4fa)

**Comment by giraud** [comment]
I don’t understand the problem. It seems you are defining 3 inner variables loc, k and x: structure looks correct.
If you duplicate x, you will get two entries with x.
I am missing something.

**Comment by giraud** [comment]
if not useful, I can remove the 'eye' icon and only top level definitions will be visible. would that 'fix' the bug ?

**Comment by jfehrle** [comment]
I was not aware of the eye icon, that hides the distracting info.  GUIs are not really self-documenting, alas.  So I would not spend time on this.  User requests are sometime contradictory (across multiple users, though hopefully individual users are self-consistent :-).

**Comment by giraud** [comment]
ok, won’t fix then.
I have updated the code to keep only one  level deep (removing record fields of inner let).
