### ISSUE TITLE
Globally opened modules don’t participate in autocomplete resolution

### ISSUE THREAD

**Issue by unleashy** [giraud/reasonml-idea-plugin#418]
plugin version: 0.114-2023.1

### Description

When coding in Rescript, the plugin doesn't seem to take globally opened modules into account. To reproduce, clone https://github.com/rescript-lang/rescript-project-template, `npm install` and try using autocomplete to write `Console.log("foo")` in some file. This project uses `@rescript/core` and opens it using `"bsc-flags": ["-open RescriptCore"]` inside `bsconfig.json`.

I would expect this to work as basically the same as how it works if you explicitly put `open RescriptCore` at the top of every file in my project.

I can work around this by simply not using that `-open` flag, but given that `@rescript/core` is supposed to be rescript’s new stdlib at some point, that seems rather unergonomic. Ideally this would work with the plugin seamlessly. Alternatively, you could add an option to provide compiler flags in the plugin's settings, so I could just add `-open RescriptCore` there.

Cheers

**Comment by giraud** [comment]
yep, only 'pervasives' is globally opened. need to read that flag.

**Comment by giraud** [comment]
also, resolution is not working with globally opened modules

**Comment by giraud** [comment]
It should be fixed in 0.116
