### ISSUE TITLE
Unbound value div

### ISSUE THREAD

**Issue by Hanaffi** [giraud/reasonml-idea-plugin#420]
plugin version: current

### Description
can't use it with rescript. it also doesn't show warnings
![image](https://github.com/giraud/reasonml-idea-plugin/assets/35642947/49002d15-531a-4979-94b0-019fbb95e136)

**Comment by giraud** [comment]
Hi, 

it’s not an error from the plugin, errors used by the plugin can be seen in the rescript tool window.
Maybe you have other plugins that are the cause of this error.

Also, if you have a problem, be more specific about it.
