### ISSUE TITLE
Structure panel Some variables have the icon indicating a functions

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#425]
plugin version: 0.115

### Description

`common` (2 entries) and `locs` in the structure panel should have a v icon ("value") instead of an f icon ("function").  IINM the `fun`s defined in each of those lines confuses the classification.

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/56852122-2f43-4d43-85fe-fa7ee085c209)

**Comment by giraud** [comment]
Fixed in 0.117

**Comment by jfehrle** [comment]
Looks good, thanks!
