### ISSUE TITLE
Structure panel shows "Unknown presentation ..." for "module X : sig ..." 

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#429]
plugin version: 0.117-2023.1

### Description

The structure panel should show the appropriate info instead of the "Unknown presentation" error message.  I suspect this is a regression--I think I would have noticed this long ago.

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/8a07b8d4-bfa8-4313-99eb-ffc2210166d3)

```
module X : sig
  type t =
    | A
    | B
end
```

**Comment by giraud** [comment]
Fixed in 0.117.1

**Comment by jfehrle** [comment]
Looks better, thanks!
