### ISSUE TITLE
No SDK created when importing a dune project

### ISSUE THREAD

**Issue by dozed** [giraud/reasonml-idea-plugin#430]
plugin version: 0.117.1-2023.2

### Description

When importing a dune project it seems that no SDK is added:

![image](https://github.com/giraud/reasonml-idea-plugin/assets/239058/993567e5-2e94-485d-9aad-528fe63d753f)

**Comment by giraud** [comment]
The import menu is no more present in latest versions of idea. Old import code is not registered anymore.
An implementation of https://plugins.jetbrains.com/docs/intellij/external-system-integration.html is needed for dune.

**Comment by giraud** [comment]
I remember why there is no more SDK, it is related to #365 . SDK is only available in intellij flavor editors and not in other like webstorm. 
When you open a ml file, there is a top banner with a link to setup opam in settings.

**Comment by giraud** [comment]
import has been updated.
when opening/importing a dune project, directories that contains a dune file are recognized has source directories.
also, when importing from sources, you can define the opam/switch during the import process
