### ISSUE TITLE
Incorrect language injection in macro

### ISSUE THREAD

**Issue by giraud** [giraud/reasonml-idea-plugin#437]
plugin version: 0.118.1

### Description

Bug extracted from #436 

Another thing is that IDE show error in this situation
![284506080-f31ff14e-3e3f-4474-987f-be4a1fcf7d50](https://github.com/giraud/reasonml-idea-plugin/assets/239612/76baee69-2539-4302-b6b7-d4448c8a4d7f)

But code compile without any errors.
Interesting thing is that: if i add spaces, problem disapear
![284506500-68911fbd-1e75-4a32-9d49-32b0069540a9](https://github.com/giraud/reasonml-idea-plugin/assets/239612/ea291ad6-c96d-4aec-ae07-0332475f2554)

**Comment by giraud** [comment]
the workaround is to use normal string (") in this case.

**Comment by giraud** [comment]
fixed in 0.119

**Comment by Qziem** [comment]
I checked new plugin version, looks working fine, thanks !
