### ISSUE TITLE
since idea 2023.3.3 update the IDE freezes while indexing, when reasonml plugin is enabled

### ISSUE THREAD

**Issue by DonBras** [giraud/reasonml-idea-plugin#457]
As soon it starts to index reason/rescript files it freezes

Even going back to 2023.3.2 doesn't work.

I use Intellij Idea Ultimate inside of wsl with xserver in windows.

Using Idea native in windows with access to the wsl path has the same issue

Only thing to work with Idea atm is to pause indexing on startup, disable reasonml plugin and restart the IDE

If you need more information about it I will try to serve you as much info as I can

**Comment by DonBras** [comment]
hm I have no windows defender running but I have to use G-Data (company policy)

but looking at the idea logs slow operations seem to be the problem
![image](https://github.com/giraud/reasonml-idea-plugin/assets/13163148/15b10590-5349-4d3a-9c49-64db49d65430)

**Comment by DonBras** [comment]
Just tried it with deactivated G-Data but still no luck. Not sure if there was any Windows 11 Update which maybe is conflicting. Only noticed this behaviour after Idea Update.

**Comment by DonBras** [comment]
Right now I can use at least the syntax-highlighting when i exclude the reason files from project modules.
![image](https://github.com/giraud/reasonml-idea-plugin/assets/13163148/9d38543d-cdba-45ff-a469-7b93e29cb720)

I also tried to checkout the project in windows. But it was the same issue. Always froze when indexing reason files.

**Comment by giraud** [comment]
do you have anything in the idea logs ?

**Comment by DonBras** [comment]
looks like the "work around" with project modules to get at least syntax highlighting does not work after reboot of the system today. I also disabled every installed plugin and left only reasonml plugin enabled.

it just stops at this point while indexing
![image](https://github.com/giraud/reasonml-idea-plugin/assets/13163148/30785cf8-0a17-4298-9a00-37c582b87c52)

but no errors in idea log, looks fine so far
![image](https://github.com/giraud/reasonml-idea-plugin/assets/13163148/035185c1-526e-4127-aff6-4a0929a5e0d5)

so it's really weird that the whole IDE freezes but no errors shown. It even does things in the background (at least in the logs) while frozen
![image](https://github.com/giraud/reasonml-idea-plugin/assets/13163148/7263c21f-2399-456e-bcd4-daf5c779048c)

but as soon i disable reasonml plugin all is fine 🤷‍♂️

**Comment by giraud** [comment]
do you know the exact module displayed in the background task popup (the `.opam/5.1.1/lib/merlin-lib/ocaml_typing/...`)

maybe you can try to dump threads from the help menu (if possible)

**Comment by DonBras** [comment]
Sorry that I couldn't get back to you earlier. It appears to be kind of random. Sometimes in freezes while going through ".opam" directory, sometimes it wents through the project until it finds a reason file, even tho the folder with the reason files was excluded in project/modules. My only workaround right now is to use vscode...

**Comment by DonBras** [comment]
Update: Today I installed the newest release of Intellij IDEA (2023.3.6) and updated the reasonml plugin and now everything works fine again 🎉
