### ISSUE TITLE
Enhancement: Structure panel: provide default tree expansion setting, etc.

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#468]
plugin version: 0.124-2023.1

### Description

These would be helpful in the structure panel:
- actions to expand or contract all nodes in the current file (note that text searching in the tree doesn't find hidden subnodes)
- a settable default to control whether to expand the structure tree automatically when I open a file.
- make "show nested expressions" a per-file setting rather than a global setting, and then
- provide a settable default for "show nested expressions" to apply when I open a file
- provide a filter setting to select whether to show variables (preferably per-file with user-settable default when you open files)  See screen shot below.  Most of the items are variables, but I'm often much more interested seeing in the functions.

~~Would you like me to split this into multiple issues?~~ [Done]

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/86f68292-60f4-4c80-b9ef-d9cabe4eb581)

**Comment by giraud** [comment]
yes, it would be better to have separate issues.
a per file settings doesn’t seem doable though
