### ISSUE TITLE
'"' in comments confuses comment recognition

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#469]
plugin version: 0.124-2023.1

### Description
The third line should be highlighted as code, not as part of a comment.  Looks like the comment recognizer doesn't handle this case.

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/29647ca2-dbfd-4c43-b0dd-0b699fbea9d4)

```
let _ = '"' in
(* '"' *)
let _ = '"' in
(* '"' *)
```

**Comment by giraud** [comment]
Fixed in 0.125

**Comment by jfehrle** [comment]
Looks good, thanks!
