### ISSUE TITLE
Enhancement: Structure panel: provide actions to expand or contract all nodes in the current file

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#470]
plugin version: 0.124-2023.1

### Description

note that text searching in the tree doesn't find hidden subnodes

See also #468

**Comment by giraud** [comment]
I think that what you want is already available in the structure panel.
![image](https://github.com/giraud/reasonml-idea-plugin/assets/239612/d72e6003-5c21-49bb-b8b9-178896d07f58)

it is accessed from the dots menu:
![image](https://github.com/giraud/reasonml-idea-plugin/assets/239612/9084524a-c0f8-48fb-96fd-e63aac78afa9)

**Comment by jfehrle** [comment]
Indeed, though in a slightly different location (not sure why your GUI looks so different):

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/e7e79dab-d6d8-4781-be73-da26cfddf90f)

**Comment by giraud** [comment]
I am using the new UI.
