### ISSUE TITLE
No Opam switch detection

### ISSUE THREAD

**Issue by MisterAssm** [giraud/reasonml-idea-plugin#480]
plugin version: 0.125 (2024.2)

### Description

Hello, I've come to ask for help because I can't get opam switch recognized at intellij. I first tried under Windows, with the same problem. Then I switched to Ubuntu and I have exactly the same problem. I'm interested if anyone has a solution.

![image](https://github.com/user-attachments/assets/604a07ca-ca06-49b5-83d5-254f2f68a18d)

**Comment by giraud** [comment]
what is the layout of your .opam directory ?

**Comment by MisterAssm** [comment]
> what is the layout of your .opam directory ?

This is what it looks like:
![image](https://github.com/user-attachments/assets/7299fe36-1439-4c1a-a75f-dcffae0e16ae)

**Comment by giraud** [comment]
looks ok, I will need to test on linux.

**Comment by MisterAssm** [comment]
No problem, if you need help, don't hesitate

**Comment by giraud** [comment]
can you install this version https://plugins.jetbrains.com/plugin/9440-reasonml/edit/versions/beta/630951 and try if it’s working ?

**Comment by giraud** [comment]
fixed in 0.126
