### ISSUE TITLE
Would like to have gutter icons on functions in modules

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#485]
plugin version: 0.123-2023.1

### Description

I've gotten used to looking at the gutter icons (like on the `module`) to tell whether a function is visible outside the current file, but this doesn't work for items in modules.  It would be very nice to add icons on both the `map_eauto` declaration and definition.  Also, it would be handy to jump to the .mli definition, e.g. when I'm changing the function parameters.

![image](https://github.com/user-attachments/assets/25f3a424-a2c5-4921-b97b-205a0434a36d)

![image](https://github.com/user-attachments/assets/90277463-1b21-4a38-9554-daf2e82bcf0a)

**Comment by giraud** [comment]
Fixed in 0.126.

![image](https://github.com/user-attachments/assets/35848fc8-03d8-45f4-9d12-4df1756cf74e)
