### ISSUE TITLE
OCaml setup on Mac OS

### ISSUE THREAD

**Issue by Pseudow** [giraud/reasonml-idea-plugin#487]
plugin version: 0.125-2024.2

### Description
I have tried to install the plugin and configure it. However, when I try to link my opam installation it doesn't work, I can't setup my sdk:
<img width="520" alt="image" src="https://github.com/user-attachments/assets/d1481db1-4291-408c-98f8-ed0bdab86667">
<img width="709" alt="image" src="https://github.com/user-attachments/assets/30490c97-c1ec-4a56-8d46-3b84ade4b0ed">

normally, it should tell me which switch to use however it doesn't and I don't have access to other librairies

**Comment by tomasvalkering** [comment]
I had the same problem, and the version you sent fixed it for me. However, now my dune project doesn't seem to be recognized by the plugin.

**Comment by Pseudow** [comment]
It works now, however I still can't manage to have full support for OCaml because I haven't been able to run a program using idea. I have to manually run the command. And there is no true support with LSP that shows the context such as errors in my syntax and so on.

**Comment by giraud** [comment]
Fixed in 0.126
